OK_AUTHENTICATED = 0
OK_RECEIVED_MESSAGE = 1
ERR_NO_SECRET_KEY = 11
INVALID_SEND_REQ = 12
INVALID_RECV_REQ = 13
INVALID_DATA = 14
ERR_SOCKET_EXCEPTION = 15
ERR_UNAUTHENTICATED_REQ = 16

#######################

BUFFER_SIZE = 4096